workflows:
  build-foodie-app:
    name: Build Foodie App
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter packages pub get
      - name: Build Foodie APK
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab